#!/usr/bin/env python3

import argparse
from typing import Any

import yaml

from lib.config import config_schema
from lib.data import Scheme
from lib.schemes.custom import gen_custom
from lib.schemes.kitty import gen_kitty
from lib.schemes.text_mate import gen_tm
from lib.schemes.vim import gen_vim

def main(config: dict[str, Any]):
    scheme = Scheme(config.get('colors', []))

    gen_vim(config['vim'], scheme)

    if 'text-mate' in config:
        gen_tm(config['text-mate'], scheme)

    if 'custom' in config:
        for custom in config['custom']:
            gen_custom(custom, scheme)

    gen_kitty(config['kitty'], scheme)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('file')

    args = parser.parse_args()
    with open(args.file, 'r') as fp:
        config = config_schema(yaml.safe_load(fp))
        main(config)
