#!/usr/bin/env python3

import argparse

import yaml

from lib.config import config_schema

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('file')

    args = parser.parse_args()
    with open(args.file, 'r') as fp:
        config = config_schema(yaml.safe_load(fp))
        print(config)
