#!/usr/bin/env python3

import argparse
import re
import sys

from lib.colors import ansi_color, str2color

def parse_color(m: re.Match[str]) -> str:
    color = m.groups()[0]
    terminator = m.groups()[2]
    return ansi_color(str2color(color), color) + terminator

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('file', nargs='?', default='-')

    args = parser.parse_args()
    if args.file == '-':
        try:
            content = sys.stdin.read()
        except KeyboardInterrupt:
            sys.exit(0)
    else:
        with open(args.file, 'r') as fp:
            content = fp.read()

    print(re.sub(r'(#([\da-f]{1,3}|[\da-f]{6}))([^\da-f])', parse_color, content))
