#!/usr/bin/env python3

import argparse
import re

from lib.colors import ansi_color, str2color

def parse_color(m: re.Match[str]) -> str:
    color = m.groups()[0]
    terminator = m.groups()[2]
    return ansi_color(str2color(color), color) + terminator

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('file')

    args = parser.parse_args()
    with open(args.file, 'r') as fp:
        print(re.sub(r'(#([\da-f]{1,3}|[\da-f]{6}))([^\da-f])', parse_color, fp.read()))
